[package]
name = "rust_impl"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-print = "0.3.4"
fixed = "1.23.1"
itertools = "0.11.0"
num = "0.4.1"
